version: '3'
services:
  rabbitmq:
    image: rabbitmq:3.9.11-management
    ports:
      - 5672:5672 #puerto para la comunicación AMQP
      - 15672:15672 #puerto para interfaz de gestión

      #este archivo define el servicio rabbitmq que utiliza la imágen rabbitmq:3.9.11 con el complemento de administración habilidado
      #los puertos 5672 y 15672 están mapeados para permitir la comunicación con rabbitMQ y acceder a la interfaz de la administración web
